### ISSUE TITLE
What is the licence on this? 

### ISSUE THREAD

**Issue by mmiscool** [chriswoodle/marlinjs#2]
Hello,
I was hoping to find out what the licence is on this.
If it was MIT I would be interested in using it.

**Comment by chriswoodle** [comment]
I thinks its ISC, Is that an issue for you?

**Comment by mmiscool** [comment]
ISC and MIT are functionally the same it seems. 

Do you mind adding the licence file in to the repo? 
https://opensource.org/licenses/ISC

**Comment by chriswoodle** [comment]
Added

**Comment by mmiscool** [comment]
Thanks!
After doing some testing this week end I should know if we will end up using this as the base to replace our existing gcode sender written in python. 
https://github.com/Autodrop3d/autodrop3dClient

Node/mom is just Soo much cleaner than using python3/pip for building things.

**Comment by chriswoodle** [comment]
Ok, let me know how well it works. I only tested this on one ramps printer for a few prints. I tried to reverse engineer information from the source code of universal Goode sender, but that was several years ago.
